### ISSUE TITLE
No effect

### ISSUE THREAD

**Issue by CodeAlDente** [corbosman/dovecot_ident#3]
Hi,

first of all thanks for sharing your work.

But it doesn't work for me. When I login, it still shows the IP of localhost.
I'm using the latest stable version RC 1.1.0 with this plugin.

**Edit:**
Forgot to mention that I'm using a IPv6 address. Is that a problem?

**Comment by corbosman** [comment]
You must be using dovecot with some specific settings. Check the roundcube mailinglist for a discussion about this topic.

**Comment by k0ste** [comment]
Just add:

```
login_trusted_networks = 127.0.0.1, ::1
```
To your dovecot configuration. Should be in README.MD
